package com.abx.ainotebook.api.edit;

import lombok.Data;

/**
 * A list of edits generated by OpenAI
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
@Data
public class EditResult {

    /**
     * The type of object returned, should be "edit"
     */
    public String object;

    /**
     * The creation time in epoch milliseconds.
     */
    public long created;
}
